### ISSUE TITLE
Gree Heatpump keeps going into AP mode

### ISSUE THREAD

**Issue by judders** [arthurkrupa/gree-hvac-mqtt-bridge#38]
Love this app. Works like a treat.
Anyone else having issues with the heatpump going back into AP mode therefor disconnects to my wifi and I can no longer talk to it with gree2mqtt.
Have setup Wifi on Heatpump using the GREE+ android app. Do I have to use the netcat command in the setup?

Thank you.

**Comment by zavenadmin** [comment]
My AC (Sinclair) was set up over a year ago and has been running without issues ever since, despite having a very unstable power supply with frequent outages and voltage drops. I used the nectar command for that, because I couldn't get the android app running.

If you're on macOS or linux, I'd recommend trying netcat (just to rule this one out). On windows, you'd have to use the linux subsystem because there are problems with CygWin (as reported in #16 )

**Comment by arthurkrupa** [comment]
My AC (Sinclair) was set up over a year ago and has been running without issues ever since, despite having a very unstable power supply with frequent outages and voltage drops. I used the nectar command for that, because I couldn't get the android app running.

If you're on macOS or linux, I'd recommend trying netcat (just to rule this one out). On windows, you'd have to use the linux subsystem because there are problems with CygWin (as reported in #16 )

**Comment by judders** [comment]
Using Alexa with my broadlink r3 causes heatpump wifi to reset.
